# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4793db0977f3286fcdf4ef09f0af3c983c5bd3aad02a140972316db22143f73faf80ccc0c6c3058368f88cb4de246266c159ec32b13188250dd77fa65cad4222

test:
  secret_key_base: 3135ed3f2e54dffa40d13ca328057b284dfb9626d71fb10153dfcfaf233f20726460f9e460415b3decbee4a359d0bb740b486cf217e934f35dd57988e2bc9be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
